
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Caregiver
 * 
 */
export type Caregiver = Prisma.CaregiverModel
/**
 * Model Keyword
 * 
 */
export type Keyword = Prisma.KeywordModel
/**
 * Model Workflow
 * 
 */
export type Workflow = Prisma.WorkflowModel
/**
 * Model WorkflowStep
 * 
 */
export type WorkflowStep = Prisma.WorkflowStepModel
/**
 * Model WorkflowOption
 * 
 */
export type WorkflowOption = Prisma.WorkflowOptionModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
/**
 * Model MessageLog
 * 
 */
export type MessageLog = Prisma.MessageLogModel
