
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkflowOption` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model WorkflowOption
 * 
 */
export type WorkflowOptionModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkflowOptionPayload>

export type AggregateWorkflowOption = {
  _count: WorkflowOptionCountAggregateOutputType | null
  _min: WorkflowOptionMinAggregateOutputType | null
  _max: WorkflowOptionMaxAggregateOutputType | null
}

export type WorkflowOptionMinAggregateOutputType = {
  id: string | null
  stepId: string | null
  optionText: string | null
  nextStepId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WorkflowOptionMaxAggregateOutputType = {
  id: string | null
  stepId: string | null
  optionText: string | null
  nextStepId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WorkflowOptionCountAggregateOutputType = {
  id: number
  stepId: number
  optionText: number
  nextStepId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type WorkflowOptionMinAggregateInputType = {
  id?: true
  stepId?: true
  optionText?: true
  nextStepId?: true
  createdAt?: true
  updatedAt?: true
}

export type WorkflowOptionMaxAggregateInputType = {
  id?: true
  stepId?: true
  optionText?: true
  nextStepId?: true
  createdAt?: true
  updatedAt?: true
}

export type WorkflowOptionCountAggregateInputType = {
  id?: true
  stepId?: true
  optionText?: true
  nextStepId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WorkflowOptionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkflowOption to aggregate.
   */
  where?: Prisma.WorkflowOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowOptions to fetch.
   */
  orderBy?: Prisma.WorkflowOptionOrderByWithRelationInput | Prisma.WorkflowOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkflowOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkflowOptions
  **/
  _count?: true | WorkflowOptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkflowOptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkflowOptionMaxAggregateInputType
}

export type GetWorkflowOptionAggregateType<T extends WorkflowOptionAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkflowOption]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkflowOption[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkflowOption[P]>
}




export type WorkflowOptionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkflowOptionWhereInput
  orderBy?: Prisma.WorkflowOptionOrderByWithAggregationInput | Prisma.WorkflowOptionOrderByWithAggregationInput[]
  by: Prisma.WorkflowOptionScalarFieldEnum[] | Prisma.WorkflowOptionScalarFieldEnum
  having?: Prisma.WorkflowOptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkflowOptionCountAggregateInputType | true
  _min?: WorkflowOptionMinAggregateInputType
  _max?: WorkflowOptionMaxAggregateInputType
}

export type WorkflowOptionGroupByOutputType = {
  id: string
  stepId: string
  optionText: string
  nextStepId: string | null
  createdAt: Date
  updatedAt: Date
  _count: WorkflowOptionCountAggregateOutputType | null
  _min: WorkflowOptionMinAggregateOutputType | null
  _max: WorkflowOptionMaxAggregateOutputType | null
}

type GetWorkflowOptionGroupByPayload<T extends WorkflowOptionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkflowOptionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkflowOptionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkflowOptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkflowOptionGroupByOutputType[P]>
      }
    >
  >



export type WorkflowOptionWhereInput = {
  AND?: Prisma.WorkflowOptionWhereInput | Prisma.WorkflowOptionWhereInput[]
  OR?: Prisma.WorkflowOptionWhereInput[]
  NOT?: Prisma.WorkflowOptionWhereInput | Prisma.WorkflowOptionWhereInput[]
  id?: Prisma.StringFilter<"WorkflowOption"> | string
  stepId?: Prisma.StringFilter<"WorkflowOption"> | string
  optionText?: Prisma.StringFilter<"WorkflowOption"> | string
  nextStepId?: Prisma.StringNullableFilter<"WorkflowOption"> | string | null
  createdAt?: Prisma.DateTimeFilter<"WorkflowOption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkflowOption"> | Date | string
  step?: Prisma.XOR<Prisma.WorkflowStepScalarRelationFilter, Prisma.WorkflowStepWhereInput>
}

export type WorkflowOptionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  optionText?: Prisma.SortOrder
  nextStepId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  step?: Prisma.WorkflowStepOrderByWithRelationInput
}

export type WorkflowOptionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkflowOptionWhereInput | Prisma.WorkflowOptionWhereInput[]
  OR?: Prisma.WorkflowOptionWhereInput[]
  NOT?: Prisma.WorkflowOptionWhereInput | Prisma.WorkflowOptionWhereInput[]
  stepId?: Prisma.StringFilter<"WorkflowOption"> | string
  optionText?: Prisma.StringFilter<"WorkflowOption"> | string
  nextStepId?: Prisma.StringNullableFilter<"WorkflowOption"> | string | null
  createdAt?: Prisma.DateTimeFilter<"WorkflowOption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkflowOption"> | Date | string
  step?: Prisma.XOR<Prisma.WorkflowStepScalarRelationFilter, Prisma.WorkflowStepWhereInput>
}, "id">

export type WorkflowOptionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  optionText?: Prisma.SortOrder
  nextStepId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.WorkflowOptionCountOrderByAggregateInput
  _max?: Prisma.WorkflowOptionMaxOrderByAggregateInput
  _min?: Prisma.WorkflowOptionMinOrderByAggregateInput
}

export type WorkflowOptionScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkflowOptionScalarWhereWithAggregatesInput | Prisma.WorkflowOptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkflowOptionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkflowOptionScalarWhereWithAggregatesInput | Prisma.WorkflowOptionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkflowOption"> | string
  stepId?: Prisma.StringWithAggregatesFilter<"WorkflowOption"> | string
  optionText?: Prisma.StringWithAggregatesFilter<"WorkflowOption"> | string
  nextStepId?: Prisma.StringNullableWithAggregatesFilter<"WorkflowOption"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorkflowOption"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"WorkflowOption"> | Date | string
}

export type WorkflowOptionCreateInput = {
  id?: string
  optionText: string
  nextStepId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  step: Prisma.WorkflowStepCreateNestedOneWithoutOptionsInput
}

export type WorkflowOptionUncheckedCreateInput = {
  id?: string
  stepId: string
  optionText: string
  nextStepId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkflowOptionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optionText?: Prisma.StringFieldUpdateOperationsInput | string
  nextStepId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  step?: Prisma.WorkflowStepUpdateOneRequiredWithoutOptionsNestedInput
}

export type WorkflowOptionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  optionText?: Prisma.StringFieldUpdateOperationsInput | string
  nextStepId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowOptionCreateManyInput = {
  id?: string
  stepId: string
  optionText: string
  nextStepId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkflowOptionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optionText?: Prisma.StringFieldUpdateOperationsInput | string
  nextStepId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowOptionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  stepId?: Prisma.StringFieldUpdateOperationsInput | string
  optionText?: Prisma.StringFieldUpdateOperationsInput | string
  nextStepId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowOptionListRelationFilter = {
  every?: Prisma.WorkflowOptionWhereInput
  some?: Prisma.WorkflowOptionWhereInput
  none?: Prisma.WorkflowOptionWhereInput
}

export type WorkflowOptionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkflowOptionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  optionText?: Prisma.SortOrder
  nextStepId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkflowOptionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  optionText?: Prisma.SortOrder
  nextStepId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkflowOptionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  optionText?: Prisma.SortOrder
  nextStepId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkflowOptionCreateNestedManyWithoutStepInput = {
  create?: Prisma.XOR<Prisma.WorkflowOptionCreateWithoutStepInput, Prisma.WorkflowOptionUncheckedCreateWithoutStepInput> | Prisma.WorkflowOptionCreateWithoutStepInput[] | Prisma.WorkflowOptionUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.WorkflowOptionCreateOrConnectWithoutStepInput | Prisma.WorkflowOptionCreateOrConnectWithoutStepInput[]
  createMany?: Prisma.WorkflowOptionCreateManyStepInputEnvelope
  connect?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
}

export type WorkflowOptionUncheckedCreateNestedManyWithoutStepInput = {
  create?: Prisma.XOR<Prisma.WorkflowOptionCreateWithoutStepInput, Prisma.WorkflowOptionUncheckedCreateWithoutStepInput> | Prisma.WorkflowOptionCreateWithoutStepInput[] | Prisma.WorkflowOptionUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.WorkflowOptionCreateOrConnectWithoutStepInput | Prisma.WorkflowOptionCreateOrConnectWithoutStepInput[]
  createMany?: Prisma.WorkflowOptionCreateManyStepInputEnvelope
  connect?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
}

export type WorkflowOptionUpdateManyWithoutStepNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowOptionCreateWithoutStepInput, Prisma.WorkflowOptionUncheckedCreateWithoutStepInput> | Prisma.WorkflowOptionCreateWithoutStepInput[] | Prisma.WorkflowOptionUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.WorkflowOptionCreateOrConnectWithoutStepInput | Prisma.WorkflowOptionCreateOrConnectWithoutStepInput[]
  upsert?: Prisma.WorkflowOptionUpsertWithWhereUniqueWithoutStepInput | Prisma.WorkflowOptionUpsertWithWhereUniqueWithoutStepInput[]
  createMany?: Prisma.WorkflowOptionCreateManyStepInputEnvelope
  set?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
  disconnect?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
  delete?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
  connect?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
  update?: Prisma.WorkflowOptionUpdateWithWhereUniqueWithoutStepInput | Prisma.WorkflowOptionUpdateWithWhereUniqueWithoutStepInput[]
  updateMany?: Prisma.WorkflowOptionUpdateManyWithWhereWithoutStepInput | Prisma.WorkflowOptionUpdateManyWithWhereWithoutStepInput[]
  deleteMany?: Prisma.WorkflowOptionScalarWhereInput | Prisma.WorkflowOptionScalarWhereInput[]
}

export type WorkflowOptionUncheckedUpdateManyWithoutStepNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowOptionCreateWithoutStepInput, Prisma.WorkflowOptionUncheckedCreateWithoutStepInput> | Prisma.WorkflowOptionCreateWithoutStepInput[] | Prisma.WorkflowOptionUncheckedCreateWithoutStepInput[]
  connectOrCreate?: Prisma.WorkflowOptionCreateOrConnectWithoutStepInput | Prisma.WorkflowOptionCreateOrConnectWithoutStepInput[]
  upsert?: Prisma.WorkflowOptionUpsertWithWhereUniqueWithoutStepInput | Prisma.WorkflowOptionUpsertWithWhereUniqueWithoutStepInput[]
  createMany?: Prisma.WorkflowOptionCreateManyStepInputEnvelope
  set?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
  disconnect?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
  delete?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
  connect?: Prisma.WorkflowOptionWhereUniqueInput | Prisma.WorkflowOptionWhereUniqueInput[]
  update?: Prisma.WorkflowOptionUpdateWithWhereUniqueWithoutStepInput | Prisma.WorkflowOptionUpdateWithWhereUniqueWithoutStepInput[]
  updateMany?: Prisma.WorkflowOptionUpdateManyWithWhereWithoutStepInput | Prisma.WorkflowOptionUpdateManyWithWhereWithoutStepInput[]
  deleteMany?: Prisma.WorkflowOptionScalarWhereInput | Prisma.WorkflowOptionScalarWhereInput[]
}

export type WorkflowOptionCreateWithoutStepInput = {
  id?: string
  optionText: string
  nextStepId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkflowOptionUncheckedCreateWithoutStepInput = {
  id?: string
  optionText: string
  nextStepId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkflowOptionCreateOrConnectWithoutStepInput = {
  where: Prisma.WorkflowOptionWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkflowOptionCreateWithoutStepInput, Prisma.WorkflowOptionUncheckedCreateWithoutStepInput>
}

export type WorkflowOptionCreateManyStepInputEnvelope = {
  data: Prisma.WorkflowOptionCreateManyStepInput | Prisma.WorkflowOptionCreateManyStepInput[]
}

export type WorkflowOptionUpsertWithWhereUniqueWithoutStepInput = {
  where: Prisma.WorkflowOptionWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkflowOptionUpdateWithoutStepInput, Prisma.WorkflowOptionUncheckedUpdateWithoutStepInput>
  create: Prisma.XOR<Prisma.WorkflowOptionCreateWithoutStepInput, Prisma.WorkflowOptionUncheckedCreateWithoutStepInput>
}

export type WorkflowOptionUpdateWithWhereUniqueWithoutStepInput = {
  where: Prisma.WorkflowOptionWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkflowOptionUpdateWithoutStepInput, Prisma.WorkflowOptionUncheckedUpdateWithoutStepInput>
}

export type WorkflowOptionUpdateManyWithWhereWithoutStepInput = {
  where: Prisma.WorkflowOptionScalarWhereInput
  data: Prisma.XOR<Prisma.WorkflowOptionUpdateManyMutationInput, Prisma.WorkflowOptionUncheckedUpdateManyWithoutStepInput>
}

export type WorkflowOptionScalarWhereInput = {
  AND?: Prisma.WorkflowOptionScalarWhereInput | Prisma.WorkflowOptionScalarWhereInput[]
  OR?: Prisma.WorkflowOptionScalarWhereInput[]
  NOT?: Prisma.WorkflowOptionScalarWhereInput | Prisma.WorkflowOptionScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkflowOption"> | string
  stepId?: Prisma.StringFilter<"WorkflowOption"> | string
  optionText?: Prisma.StringFilter<"WorkflowOption"> | string
  nextStepId?: Prisma.StringNullableFilter<"WorkflowOption"> | string | null
  createdAt?: Prisma.DateTimeFilter<"WorkflowOption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorkflowOption"> | Date | string
}

export type WorkflowOptionCreateManyStepInput = {
  id?: string
  optionText: string
  nextStepId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkflowOptionUpdateWithoutStepInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optionText?: Prisma.StringFieldUpdateOperationsInput | string
  nextStepId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowOptionUncheckedUpdateWithoutStepInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optionText?: Prisma.StringFieldUpdateOperationsInput | string
  nextStepId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowOptionUncheckedUpdateManyWithoutStepInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optionText?: Prisma.StringFieldUpdateOperationsInput | string
  nextStepId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type WorkflowOptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  stepId?: boolean
  optionText?: boolean
  nextStepId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  step?: boolean | Prisma.WorkflowStepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowOption"]>

export type WorkflowOptionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  stepId?: boolean
  optionText?: boolean
  nextStepId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  step?: boolean | Prisma.WorkflowStepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowOption"]>

export type WorkflowOptionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  stepId?: boolean
  optionText?: boolean
  nextStepId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  step?: boolean | Prisma.WorkflowStepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowOption"]>

export type WorkflowOptionSelectScalar = {
  id?: boolean
  stepId?: boolean
  optionText?: boolean
  nextStepId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type WorkflowOptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "stepId" | "optionText" | "nextStepId" | "createdAt" | "updatedAt", ExtArgs["result"]["workflowOption"]>
export type WorkflowOptionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  step?: boolean | Prisma.WorkflowStepDefaultArgs<ExtArgs>
}
export type WorkflowOptionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  step?: boolean | Prisma.WorkflowStepDefaultArgs<ExtArgs>
}
export type WorkflowOptionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  step?: boolean | Prisma.WorkflowStepDefaultArgs<ExtArgs>
}

export type $WorkflowOptionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkflowOption"
  objects: {
    step: Prisma.$WorkflowStepPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    stepId: string
    optionText: string
    nextStepId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["workflowOption"]>
  composites: {}
}

export type WorkflowOptionGetPayload<S extends boolean | null | undefined | WorkflowOptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload, S>

export type WorkflowOptionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkflowOptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkflowOptionCountAggregateInputType | true
  }

export interface WorkflowOptionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkflowOption'], meta: { name: 'WorkflowOption' } }
  /**
   * Find zero or one WorkflowOption that matches the filter.
   * @param {WorkflowOptionFindUniqueArgs} args - Arguments to find a WorkflowOption
   * @example
   * // Get one WorkflowOption
   * const workflowOption = await prisma.workflowOption.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkflowOptionFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkflowOptionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkflowOptionClient<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkflowOption that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkflowOptionFindUniqueOrThrowArgs} args - Arguments to find a WorkflowOption
   * @example
   * // Get one WorkflowOption
   * const workflowOption = await prisma.workflowOption.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkflowOptionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkflowOptionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowOptionClient<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkflowOption that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowOptionFindFirstArgs} args - Arguments to find a WorkflowOption
   * @example
   * // Get one WorkflowOption
   * const workflowOption = await prisma.workflowOption.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkflowOptionFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkflowOptionFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkflowOptionClient<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkflowOption that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowOptionFindFirstOrThrowArgs} args - Arguments to find a WorkflowOption
   * @example
   * // Get one WorkflowOption
   * const workflowOption = await prisma.workflowOption.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkflowOptionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkflowOptionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowOptionClient<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkflowOptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowOptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkflowOptions
   * const workflowOptions = await prisma.workflowOption.findMany()
   * 
   * // Get first 10 WorkflowOptions
   * const workflowOptions = await prisma.workflowOption.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workflowOptionWithIdOnly = await prisma.workflowOption.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkflowOptionFindManyArgs>(args?: Prisma.SelectSubset<T, WorkflowOptionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkflowOption.
   * @param {WorkflowOptionCreateArgs} args - Arguments to create a WorkflowOption.
   * @example
   * // Create one WorkflowOption
   * const WorkflowOption = await prisma.workflowOption.create({
   *   data: {
   *     // ... data to create a WorkflowOption
   *   }
   * })
   * 
   */
  create<T extends WorkflowOptionCreateArgs>(args: Prisma.SelectSubset<T, WorkflowOptionCreateArgs<ExtArgs>>): Prisma.Prisma__WorkflowOptionClient<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkflowOptions.
   * @param {WorkflowOptionCreateManyArgs} args - Arguments to create many WorkflowOptions.
   * @example
   * // Create many WorkflowOptions
   * const workflowOption = await prisma.workflowOption.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkflowOptionCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkflowOptionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkflowOptions and returns the data saved in the database.
   * @param {WorkflowOptionCreateManyAndReturnArgs} args - Arguments to create many WorkflowOptions.
   * @example
   * // Create many WorkflowOptions
   * const workflowOption = await prisma.workflowOption.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkflowOptions and only return the `id`
   * const workflowOptionWithIdOnly = await prisma.workflowOption.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkflowOptionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkflowOptionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkflowOption.
   * @param {WorkflowOptionDeleteArgs} args - Arguments to delete one WorkflowOption.
   * @example
   * // Delete one WorkflowOption
   * const WorkflowOption = await prisma.workflowOption.delete({
   *   where: {
   *     // ... filter to delete one WorkflowOption
   *   }
   * })
   * 
   */
  delete<T extends WorkflowOptionDeleteArgs>(args: Prisma.SelectSubset<T, WorkflowOptionDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkflowOptionClient<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkflowOption.
   * @param {WorkflowOptionUpdateArgs} args - Arguments to update one WorkflowOption.
   * @example
   * // Update one WorkflowOption
   * const workflowOption = await prisma.workflowOption.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkflowOptionUpdateArgs>(args: Prisma.SelectSubset<T, WorkflowOptionUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkflowOptionClient<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkflowOptions.
   * @param {WorkflowOptionDeleteManyArgs} args - Arguments to filter WorkflowOptions to delete.
   * @example
   * // Delete a few WorkflowOptions
   * const { count } = await prisma.workflowOption.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkflowOptionDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkflowOptionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkflowOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowOptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkflowOptions
   * const workflowOption = await prisma.workflowOption.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkflowOptionUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkflowOptionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkflowOptions and returns the data updated in the database.
   * @param {WorkflowOptionUpdateManyAndReturnArgs} args - Arguments to update many WorkflowOptions.
   * @example
   * // Update many WorkflowOptions
   * const workflowOption = await prisma.workflowOption.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkflowOptions and only return the `id`
   * const workflowOptionWithIdOnly = await prisma.workflowOption.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkflowOptionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkflowOptionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkflowOption.
   * @param {WorkflowOptionUpsertArgs} args - Arguments to update or create a WorkflowOption.
   * @example
   * // Update or create a WorkflowOption
   * const workflowOption = await prisma.workflowOption.upsert({
   *   create: {
   *     // ... data to create a WorkflowOption
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkflowOption we want to update
   *   }
   * })
   */
  upsert<T extends WorkflowOptionUpsertArgs>(args: Prisma.SelectSubset<T, WorkflowOptionUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkflowOptionClient<runtime.Types.Result.GetResult<Prisma.$WorkflowOptionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkflowOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowOptionCountArgs} args - Arguments to filter WorkflowOptions to count.
   * @example
   * // Count the number of WorkflowOptions
   * const count = await prisma.workflowOption.count({
   *   where: {
   *     // ... the filter for the WorkflowOptions we want to count
   *   }
   * })
  **/
  count<T extends WorkflowOptionCountArgs>(
    args?: Prisma.Subset<T, WorkflowOptionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkflowOptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkflowOption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowOptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkflowOptionAggregateArgs>(args: Prisma.Subset<T, WorkflowOptionAggregateArgs>): Prisma.PrismaPromise<GetWorkflowOptionAggregateType<T>>

  /**
   * Group by WorkflowOption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowOptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkflowOptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkflowOptionGroupByArgs['orderBy'] }
      : { orderBy?: WorkflowOptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkflowOptionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkflowOptionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkflowOption model
 */
readonly fields: WorkflowOptionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkflowOption.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkflowOptionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  step<T extends Prisma.WorkflowStepDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkflowStepDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkflowOption model
 */
export interface WorkflowOptionFieldRefs {
  readonly id: Prisma.FieldRef<"WorkflowOption", 'String'>
  readonly stepId: Prisma.FieldRef<"WorkflowOption", 'String'>
  readonly optionText: Prisma.FieldRef<"WorkflowOption", 'String'>
  readonly nextStepId: Prisma.FieldRef<"WorkflowOption", 'String'>
  readonly createdAt: Prisma.FieldRef<"WorkflowOption", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"WorkflowOption", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorkflowOption findUnique
 */
export type WorkflowOptionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowOption to fetch.
   */
  where: Prisma.WorkflowOptionWhereUniqueInput
}

/**
 * WorkflowOption findUniqueOrThrow
 */
export type WorkflowOptionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowOption to fetch.
   */
  where: Prisma.WorkflowOptionWhereUniqueInput
}

/**
 * WorkflowOption findFirst
 */
export type WorkflowOptionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowOption to fetch.
   */
  where?: Prisma.WorkflowOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowOptions to fetch.
   */
  orderBy?: Prisma.WorkflowOptionOrderByWithRelationInput | Prisma.WorkflowOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkflowOptions.
   */
  cursor?: Prisma.WorkflowOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowOptions.
   */
  distinct?: Prisma.WorkflowOptionScalarFieldEnum | Prisma.WorkflowOptionScalarFieldEnum[]
}

/**
 * WorkflowOption findFirstOrThrow
 */
export type WorkflowOptionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowOption to fetch.
   */
  where?: Prisma.WorkflowOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowOptions to fetch.
   */
  orderBy?: Prisma.WorkflowOptionOrderByWithRelationInput | Prisma.WorkflowOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkflowOptions.
   */
  cursor?: Prisma.WorkflowOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowOptions.
   */
  distinct?: Prisma.WorkflowOptionScalarFieldEnum | Prisma.WorkflowOptionScalarFieldEnum[]
}

/**
 * WorkflowOption findMany
 */
export type WorkflowOptionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowOptions to fetch.
   */
  where?: Prisma.WorkflowOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowOptions to fetch.
   */
  orderBy?: Prisma.WorkflowOptionOrderByWithRelationInput | Prisma.WorkflowOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkflowOptions.
   */
  cursor?: Prisma.WorkflowOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowOptions.
   */
  distinct?: Prisma.WorkflowOptionScalarFieldEnum | Prisma.WorkflowOptionScalarFieldEnum[]
}

/**
 * WorkflowOption create
 */
export type WorkflowOptionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkflowOption.
   */
  data: Prisma.XOR<Prisma.WorkflowOptionCreateInput, Prisma.WorkflowOptionUncheckedCreateInput>
}

/**
 * WorkflowOption createMany
 */
export type WorkflowOptionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkflowOptions.
   */
  data: Prisma.WorkflowOptionCreateManyInput | Prisma.WorkflowOptionCreateManyInput[]
}

/**
 * WorkflowOption createManyAndReturn
 */
export type WorkflowOptionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * The data used to create many WorkflowOptions.
   */
  data: Prisma.WorkflowOptionCreateManyInput | Prisma.WorkflowOptionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkflowOption update
 */
export type WorkflowOptionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkflowOption.
   */
  data: Prisma.XOR<Prisma.WorkflowOptionUpdateInput, Prisma.WorkflowOptionUncheckedUpdateInput>
  /**
   * Choose, which WorkflowOption to update.
   */
  where: Prisma.WorkflowOptionWhereUniqueInput
}

/**
 * WorkflowOption updateMany
 */
export type WorkflowOptionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkflowOptions.
   */
  data: Prisma.XOR<Prisma.WorkflowOptionUpdateManyMutationInput, Prisma.WorkflowOptionUncheckedUpdateManyInput>
  /**
   * Filter which WorkflowOptions to update
   */
  where?: Prisma.WorkflowOptionWhereInput
  /**
   * Limit how many WorkflowOptions to update.
   */
  limit?: number
}

/**
 * WorkflowOption updateManyAndReturn
 */
export type WorkflowOptionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * The data used to update WorkflowOptions.
   */
  data: Prisma.XOR<Prisma.WorkflowOptionUpdateManyMutationInput, Prisma.WorkflowOptionUncheckedUpdateManyInput>
  /**
   * Filter which WorkflowOptions to update
   */
  where?: Prisma.WorkflowOptionWhereInput
  /**
   * Limit how many WorkflowOptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkflowOption upsert
 */
export type WorkflowOptionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkflowOption to update in case it exists.
   */
  where: Prisma.WorkflowOptionWhereUniqueInput
  /**
   * In case the WorkflowOption found by the `where` argument doesn't exist, create a new WorkflowOption with this data.
   */
  create: Prisma.XOR<Prisma.WorkflowOptionCreateInput, Prisma.WorkflowOptionUncheckedCreateInput>
  /**
   * In case the WorkflowOption was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkflowOptionUpdateInput, Prisma.WorkflowOptionUncheckedUpdateInput>
}

/**
 * WorkflowOption delete
 */
export type WorkflowOptionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
  /**
   * Filter which WorkflowOption to delete.
   */
  where: Prisma.WorkflowOptionWhereUniqueInput
}

/**
 * WorkflowOption deleteMany
 */
export type WorkflowOptionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkflowOptions to delete
   */
  where?: Prisma.WorkflowOptionWhereInput
  /**
   * Limit how many WorkflowOptions to delete.
   */
  limit?: number
}

/**
 * WorkflowOption without action
 */
export type WorkflowOptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowOption
   */
  select?: Prisma.WorkflowOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowOption
   */
  omit?: Prisma.WorkflowOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowOptionInclude<ExtArgs> | null
}
